### PR TITLE
Fb fix undefined variable notice

### LINKED ISSUE #18: Fix notice when testing Varnish connection
Notice: Undefined variable: wpv_blogaddr in /UCF-WordPress-Varnish-as-a-Service/wordpress-varnish-as-a-service.php on line 449 

Notice gets thrown after clicking one of the "Test Connection to Varnish" buttons in the VaaS admin page.

https://github.com/UCF/UCF-WordPress-Varnish-as-a-Service/blob/master/wordpress-varnish-as-a-service.php#L449

### PR DESCRIPTION
**Pull request by vinhtvu2**
Fix this issue:
https://github.com/UCF/UCF-WordPress-Varnish-as-a-Service/issues/18

### CODE REVIEW

File: wordpress-varnish-as-a-service.php [hunk 1]
```diff
@@ -55,6 +55,10 @@ public function __construct() {
 		add_action('add_attachment', array(&$this, 'WPVarnishPurgeAttachment'), 99);
 		add_action('edit_attachment', array(&$this, 'WPVarnishPurgeAttachment'), 99);
 		add_action('delete_attachment', array(&$this, 'WPVarnishPurgeAttachment'), 99);
+		add_action('wp_update_nav_menu', array(&$this, 'WPVarnishPurgeAll'), 99);
```
Comment (cjg89) [inline wordpress-varnish-as-a-service.php:58]: These menu action hooks have already been approved + merged into rc, correct?

**Review by cjg89 — APPROVED** [review]

File: wordpress-varnish-as-a-service.php (hunk 1 above)
Comment (vinhtvu2) [reply wordpress-varnish-as-a-service.php:58]: They were approved and merged in. Not sure why it's still showing up here. I'll see if it cause conflict when I merge in.
